### ISSUE TITLE
The links in the footer collide with the text.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#32]
## Describe the bug
The links in the footer collide with the text when we click on the links.

### To reproduce
1. Go to 'fluidproject.org'
2. Click on links present in the left side of the footer.
3. See error

### Expected behavior
The links should not collide when clicked.

## Screenshots
![Screenshot from 2020-03-02 00-04-13](https://user-images.githubusercontent.com/55639487/75631662-dc1cc700-5c1a-11ea-9a57-314ba4517e00.png)

### Desktop
 - OS: [e.g. Ubuntu 18.04]
 - Browser [e.g. chrome]

**Comment by neetigyachahar** [comment]
Well, I researched a bit and it seems that its practically impossible to change shape of outline. As in our case we want to decrease the height but maintaining the width. The  ```outline-offset```  also reduces the width hence now outline overlays with inner text.
Best solution could be to use borders for focusing.
Your views?

**Comment by jobara** [comment]
@neetigyachahar what was the need for changing the shape of the outline, or maybe I'm not understanding exactly what you mean by that.

**Comment by aashimgarg** [comment]
@jobara actually the borders are colliding with the text when we clink the links.

**Comment by aashimgarg** [comment]
@jobara The outline-offset property adds space between an outline and the edge or border of an element. It does not change the shape of the outline.

**Comment by sachin10101998** [comment]
> Well, I researched a bit and it seems that it's practically impossible to change the shape of the outline.

@neetigyachahar why do we have to change the outline-offset property for solving this?

> As in our case we want to decrease the height

Don't we intend to decrease the thickness of the outline because the outline is overlapping with text.
Here's a screenshot with reduced outline thickness:
 ![Screenshot from 2020-03-04 06-17-45](https://user-images.githubusercontent.com/34926285/75833941-90b41580-5de0-11ea-82db-d6dc5278a05d.png)
I think this aptly solves this issue.

**Comment by neetigyachahar** [comment]
@jobara By changing shape I mean we need to keep the width of the outline same but decrease the height.

@sachin10101998 I tried that with the lower link and the overlap is still there (with 'g' here). Check this:
![image](https://user-images.githubusercontent.com/42602123/75890698-bbd84c80-5e54-11ea-9905-8a94280cb199.png)

I was able to create a **quick fix** using padding, margin and outline-offset properties.
![image](https://user-images.githubusercontent.com/42602123/75893520-efb57100-5e58-11ea-94a3-37270b60a78e.png)
![image](https://user-images.githubusercontent.com/42602123/75893699-3905c080-5e59-11ea-92aa-8651fe367415.png)

Actually a css property ```line-height: inherit;```  to `<p>` is present which made the lines look more compact. But they actually overlapped. 
![image](https://user-images.githubusercontent.com/42602123/75897720-02cb3f80-5e5f-11ea-8d12-ed5f532d9cd7.png)

Instead using ```line-height: initial;``` on `<p>` seems to work best.


### System details
* OS: Zorin OS 15.1
* Browser: Chrome 80.0

**Comment by aashimgarg** [comment]
Yes @neetigyachahar by changing he width of the outline we can change it but the g will collide with the outline.

**Comment by aashimgarg** [comment]
@jobara we cannot change the style as in the code the styles are the gitignore files.

**Comment by sachin10101998** [comment]
@neetigyachahar I use Ubuntu 18.04 with the latest chrome and the overlapping isn't as distinct as it is on your platform. 
I didn't get how changing line-height to initial will solve this since we are not assigning any explicit line-height value to the p tag. Both inherited and initial values are 1.2em by default for the lowest line spacing set in the preferences column. Can you specify your platform details?
Screenshots:
![Screenshot from 2020-03-04 22-27-47](https://user-images.githubusercontent.com/34926285/75903853-38285b00-5e68-11ea-9c16-208f726eae3a.png)

> we cannot change the style as in the code the styles are the .gitignore files.

.gitignore files contain the files which are not to be uploaded to GitHub. The files built by Docpad (out) and style files created by stylus are not uploaded here. You don't need them to change style files. You can run a local server and change the style files.

**Comment by aashimgarg** [comment]
Yes we can change the styles in the local server but we cannot push the commits.

**Comment by sachin10101998** [comment]
@aashimgarg why can't you push those commits?

**Comment by jobara** [comment]
@neetigyachahar when you illustrate code/markup/styling changes, please write them in text and place them in a properly formatted code block using markdown. It will be easier to read and make use of later. Also it will help those that can't view your images to know the suggested change.

**Comment by jobara** [comment]
Trying to summarize things so far. The outline is overlapping the text above and below, potentially due to line-height and outline thickness. Although this is less prevalent on different platforms/browsers? Did I get that all correctly?

**Comment by aashimgarg** [comment]
yes @jobara the outline thickness is colliding with the text.

**Comment by neetigyachahar** [comment]
@sachin10101998 I would suggest you to try selecting the text in footer and compare if you have an overlap like that of mine.
![image](https://user-images.githubusercontent.com/42602123/76142163-02b28600-6091-11ea-90b7-b2be8e80fc71.png)
Because this could be the underlying issue creating the outline overlap with other text.
My OS is **Zorin OS 15.1** which is just UI modification of **Ubuntu Bionic Beaver 18.04.2 LTS**.
The browser I am using is **Google Chrome Version 80.0.3987.116**.

@jobara I would take care of adding such illustrations as code blocks in markdown from now on. I have edited the https://github.com/fluid-project/fluidproject.org/issues/32#issuecomment-594627891 .

**Comment by cggvuhh** [comment]
Can anyone tell that is inclusion design institute organisation applying for  2021gsoc 

@jobara @avtar @cindlyi

**Comment by colinbdclark** [comment]
Hi @cggvuhh. It's not appropriate to use Github Issues to ask questions like this, especially since you've posted the same message multiple times to a number of different issues. The short answer: we don't know if we will apply for GSOC in 2021.

If you are interested in contributing to our community, please have a look at [the resources we created for GSoC students](https://wiki.fluidproject.org/display/fluid/Google+Summer+of+Code+2020+with+the+Fluid+Project) and our [Get Involved page](https://wiki.fluidproject.org/display/fluid/Get+Involved). We are a very busy and committed community, and while we very much appreciate contributions from anyone, we are not always in a position to be able to answer questions that we've already documented elsewhere. Thank you for your interest in our work.

**Comment by cggvuhh** [comment]
@colinbdclark I ask because I see your gsoc selection process
Inclusion design institute select in 
------2016
Then 
------2018
Then 
------2020
It means 2022 not in 2021 that's why I asking

**Comment by cggvuhh** [comment]
Plz reply @jobara

**Comment by colinbdclark** [comment]
@cggvuhh, I've already responded to your question. We simply don't know if we'll apply next year, nor do we know if we will be accepted. This is not the appropriate place to ask the questions you are asking, please stop. You can refer to the resources I shared with you above if you're interested in contributing to our community constructively.
