### ISSUE TITLE
Open In New Tab doesn't work

### ISSUE THREAD

**Issue by akhillllldev** [fluid-project/fluidproject.org#44]
Isn't this symbol supposed to be - "Open in new tab"?

## Screenshots
![Screenshot from 2020-03-19 12-56-36](https://user-images.githubusercontent.com/40662846/77042187-41c1cf00-69e1-11ea-8eb6-8efa86183fd7.png)

**Comment by jobara** [comment]
@akhillllldev it's being used to identify that it is an external link, one that will go to a new site. Also please add more detail and description to the Issues. It's hard for those that cannot view/perceive the image to understand what the issue is. Also a link to the specific page would be helpful.
