### ISSUE TITLE
background color of the text

### ISSUE THREAD

**Issue by samagragupta** [fluid-project/fluidproject.org#47]
The background color of the text should be transparent.
As it would look good.
![Capture](https://user-images.githubusercontent.com/32234926/77219991-444b3280-6b61-11ea-9098-fed815f5419b.JPG)

**Comment by sachin10101998** [comment]
@samagragupta please follow the described issue template while you report an issue. Also, make sure that you provide description when you post an image so that to make sure that people who can't visualize these images understand what you are trying to say. From the image, I guess you are trying to point to https://fluidproject.org/projects.html page. It has been kept this way on purpose so that text does not interfere with the faded texts or images in the background picture. On changing the contrast/theme, the white box disappears. 
![Screenshot from 2020-03-23 18-01-31](https://user-images.githubusercontent.com/34926285/77316986-5f1fd180-6d30-11ea-8d0a-4b14009073a0.png)

**Comment by Aarize29** [comment]
May I contribute?

**Comment by huamanraj** [comment]
please assign me for this issue!

**Comment by greatislander** [comment]
Hi, we won't be making this change at the moment.
